### ISSUE TITLE
Unable to unzip file in macOS Catalina - Error 79

### ISSUE THREAD

**Issue by mzaremski** [cthackers/adm-zip#297] opened 2019-10-22 14:02 UTC
Hello!
I use `adm-zip` (I try with `0.4.11`,`0.4.13`) in a server to zip files and send them to users. It worked very well and it zip files correctly, but users with macOS Catalina have this error:
`(Error 79 - Inappropriate file type or format.)`

In the app, I have changed this package to another and it working well with Catalina and Mojave os, so I assume that this problem is with `adm-zip` package.

I have also checked with `unzip` command and it works fine.

**Comment by curran** [comment] 2019-10-24 06:50
Possible duplicate of https://github.com/cthackers/adm-zip/issues/289

**Comment by paulsUsername** [comment] 2020-01-30 13:06
This still is happening for me

**Comment by hacknhustle** [comment] 2020-02-24 05:24
Just updated this package to 0.4.14 and it's fixed the problem for me.

**Comment by 5saviahv** [comment] 2021-03-09 06:21
It seems to be fixed now

**Closed by 5saviahv** 2021-03-09 06:21 UTC

**Comment by wzs1234566** [comment] 2024-02-28 02:58
using 0.5.10 and it's giving me the same error
