### ISSUE TITLE
Wrong checksum (?)

### ISSUE THREAD

**Issue by Hongbo-Miao** [cthackers/adm-zip#288] opened 2019-07-15 21:16 UTC
I am using

- macOS 10.14.5
- adm-zip 0.4.13

After I uncompress and compress again of a zip file (images inside) by the code below

```js
const AdmZip = require('adm-zip');

const newZip = new AdmZip();
const zip = new AdmZip('./original.zip');
const zipEntries = zip.getEntries();

zipEntries.forEach((zipEntry) => {
  const fileName = zipEntry.entryName;
  const fileContent = zip.readFile(fileName);
  newZip.addFile(fileName, fileContent, '');
});
newZip.writeZip('./test.zip');
```

I can uncompress by macOS default **Achieve Utility** app successfully, however I failed to uncompress it by other applications such as [**The Unarchiver**](https://apps.apple.com/us/app/the-unarchiver/id425424353?mt=12) and [**FolkLift**](https://binarynights.com).

Based on FolkLift’s error, it seems like wrong checksum (?)

![image](https://user-images.githubusercontent.com/3375461/61249461-22fc9180-a70a-11e9-8e31-c611a037a719.png)

![image](https://user-images.githubusercontent.com/3375461/61249443-15dfa280-a70a-11e9-9c79-fbf83f2cc6aa.png)

**Comment by curran** [comment] 2019-10-24 06:51
Possible duplicate of https://github.com/cthackers/adm-zip/issues/289

**Comment by 5saviahv** [comment] 2021-03-09 06:24
It seems to be fixed now

**Closed by 5saviahv** 2021-03-09 06:24 UTC
