### ISSUE TITLE
Published npm version out of sync with GitHub, and has crc problem

### ISSUE THREAD

**Issue by gid-elect** [cthackers/adm-zip#286] opened 2019-06-28 14:06 UTC
Hi – thanks for adm-zip – very useful. I was having difficulty opening created zip files in PowerPoint and tracked it down to the CRC fields being written out as 16-bit values instead of 32. I see that's been fixed in the latest version on GitHub (0.4.12), but the published version on npm (0.4.13) doesn't include the fix. Is it possible to publish the latest version on npm, perhaps as 0.4.14...?

**Comment by ozelot379** [comment] 2019-08-10 11:21
https://github.com/cthackers/adm-zip/issues/289#issuecomment-520140501

**Comment by curran** [comment] 2019-10-24 06:51
Possible duplicate of https://github.com/cthackers/adm-zip/issues/289

**Closed** 2020-11-19 21:53 UTC
