### ISSUE TITLE
Windows 7 created zip files corrupted or creates system protected files

### ISSUE THREAD

**Issue by gacekssj4** [cthackers/adm-zip#142] opened 2015-06-07 10:47 UTC
When I pack files into zip with adm-zip and then unpack them with winzip, they're either corrupted, or if they unpack, the folder seems empty. But when i check in windows option to show system hidden files they appear.
In properties they have flag "hidden" which is read only and cannot unhide files.

**Comment by alanhamlett** [comment] 2015-07-01 20:11
Duplicate of 130

**Closed** 2024-06-26 06:20 UTC
