### ISSUE TITLE
writeZip CAN'T WORK

### ISSUE THREAD

**Issue by iNahooNya** [cthackers/adm-zip#290] opened 2019-08-11 10:44 UTC
Version: v0.4.9 ~ v0.4.13
MacOS HS 10.13.6

## Demo
Seems simple
```javascript
const AdmZip = require('adm-zip');
const run = f => f();

run(async () => {
    const zip = new AdmZip(__dirname + '/TEST1.zip');
    await new Promise((resolve, reject) => {
        zip.writeZip(__dirname + '/output2.zip', err => {
            if (err) {
                reject(err);
            }
            resolve();
        });
    });
});

```

The TEST1.zip is an image
![image](https://user-images.githubusercontent.com/12727349/62832756-33028500-bc66-11e9-9ab9-bd00f288faef.png)

Then I try to run this script
![image](https://user-images.githubusercontent.com/12727349/62832764-59282500-bc66-11e9-9008-7a9f11049d1a.png)

Then I try to unzip it
![image](https://user-images.githubusercontent.com/12727349/62832809-f5522c00-bc66-11e9-8653-5c79d29da9e6.png)

BOOM!

## Guest
When I try to use command unzip.

![image](https://user-images.githubusercontent.com/12727349/62832876-d86a2880-bc67-11e9-97d6-68e40bdcf796.png)

And I don't know what it means.

**Comment by iNahooNya** [comment] 2019-08-11 10:48
By the way.
If I archive a json file , and use this writeZip output continue, like that
```javascript
const zip = new AdmZip(__dirname + '/output2.zip');
zip.getEntry('xxx.json').getData().toString('utf-8');
```
And I will recived and long non-printable character string.

**Comment by 5saviahv** [comment] 2020-11-16 10:21
First issue was caused by typo in adm-zip code. You can see from screen shot "2991f8cb" becomes 0000f8cb because of this typo. Sadly it was even in npm repository with this typo. This issue was fixed in github but updating npm took some time.

**Closed** 2020-11-19 21:53 UTC
