### ISSUE TITLE
Is there a way to rename the file name when using extractEntryTo?

### ISSUE THREAD

**Issue by amit2maha1** [cthackers/adm-zip#321] opened 2020-07-17 19:01 UTC

**Comment by amit2maha1** [comment] 2020-07-17 19:14
For now I am doing this:

```
admZipFile.addFile('customName', Buffer.alloc(admZipFile.readFile(zipEntries[1].entryName).length, admZipFile.readFile(zipEntries[1].entryName)))
admZipFile.deleteFile(zipEntries[1].entryName)
```

thank you for making adm-zip, you guys are lifesavers

**Comment by jschuur** [comment] 2020-08-30 10:53
Duplicate of #318

**Comment by cthackers** [comment] 2020-11-19 21:33
added

**Closed by cthackers** 2020-11-19 21:33 UTC
